import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="relative min-h-screen">
          {/* ✅ 배경 이미지 */}
          <Image
            src="/images/LandingImg.png"
            alt="bg-img"
            fill
            style={{
              objectFit: "cover",
              zIndex: -1,
            }}
          />
        {children}
        </div>
      </body>
    </html>
  );
}
